### ISSUE TITLE
def --wrapped

### ISSUE THREAD

**Issue by RGBCube** [bew/dotfiles#87]
```nu
def --wrapped mywrapperofx [..anyargsorflags] {
  x $anyargsorflags
}
```

Saw the note in your alias config, this is what you might be looking for.

**Comment by bew** [comment]
You're referring to this comment I believe?
https://github.com/bew/dotfiles/blob/8cfc1a29a3b2f9c681b7c472abc1426fd434021f/nushell/bewcfg_aliases_and_short_funcs.nu#L45-46

The idea would be to replicate this zsh function:
https://github.com/bew/dotfiles/blob/8cfc1a29a3b2f9c681b7c472abc1426fd434021f/zsh/rc/aliases_and_short_funcs.zsh#L310-322

I'm still not sure completion will work with the wrapper, how does it detects which completion functions to call? I don't see a way to tell nushell what to use as the prefix 🤔
Or is it 'magic' by tracking where the given args are used?

(I'll try to test your suggestion soon)

**Comment by RGBCube** [comment]
I'm not sure how completions will work, but maybe, maybe, Nu detects the command you are wrapping if you do not have a custom completer.

**Comment by bew** [comment]
Thanks, I was able to implement my `nosudo` command using that in https://github.com/bew/dotfiles/commit/a7738ce1a3ebb324709204b321a69ff699f349a5 👍

I'm still missing the completions though
